import {
    Person,
    Apartment,
    Public,
    Work,
    School,
    EmojiEvents,
    AutoStories,
    Redeem,
    ShapeLine,
    Language,
    OutdoorGrill,
    Groups,
    Handshake,
  } from "@mui/icons-material";
  
// Create an array for all the necessary section links in the Navigation Bar

export const navLinks = [
    {
      id: 1,
      title: "Basics",
      ariaLabel: "basics",
      href: "#",
      icon: <Person />,
    },
    {
      id: 2,
      title: "Location",
      ariaLabel: "location",
      href: "#",
      icon: <Apartment />,
    },
    {
      id: 3,
      title: "Socials",
      ariaLabel: "socials",
      href: "#",
      icon: <Public />,
    },
    {
      id: 4,
      title: "Education",
      ariaLabel: "education",
      href: "#",
      icon: <School />,
    },
    {
      id: 5,
      title: "Work Experience",
      ariaLabel: "work-experience",
      href: "#",
      icon: <Work />,
    },
    {
      id: 6,
      title: "Projects",
      ariaLabel: "projects",
      href: "#",
      icon: <Groups />,
    },
    {
      id: 7,
      title: "Skills",
      ariaLabel: "skills",
      href: "#",
      icon: <ShapeLine />,
    },
    {
      id: 8,
      title: "Certifications",
      ariaLabel: "certifications",
      href: "#",
      icon: <Redeem />,
    },
    {
      id: 9,
      title: "Awards",
      ariaLabel: "awards",
      href: "#",
      icon: <EmojiEvents />,
    },
    {
      id: 10,
      title: "Interests",
      ariaLabel: "interests",
      href: "#",
      icon: <OutdoorGrill />,
    },
    {
      id: 11,
      title: "Languages",
      ariaLabel: "languages",
      href: "#",
      icon: <Language />,
    },
    {
      id: 12,
      title: "Publications",
      ariaLabel: "publications",
      href: "#",
      icon: <AutoStories />,
    },
    {
      id: 13,
      title: "References",
      ariaLabel: "references",
      href: "#",
      icon: <Handshake />,
    },
  ];